nextstrain/cli

nextstrain/cli/command/build.py, nextstrain/cli/command/view.py, nextstrain/cli/runner/docker.py, nextstrain/cli/util.py
Resolves #7.
See commits for rationales.
=> Gracefully handle missing paths

nextstrain/cli/command/view.py
Auspice ≥1.35.2 includes a CLI which should be used to run Auspice going
forward, the invocation of which is slightly different than the previous
wrapper script.
This relies on the corresponding change in the base Docker image.
=> view: Update for Auspice ≥1.35.2

nextstrain/cli/command/view.py, nextstrain/cli/runner/__init__.py, nextstrain/cli/runner/aws_batch/__init__.py, nextstrain/cli/runner/aws_batch/jobs.py, nextstrain/cli/runner/docker.py, nextstrain/cli/runner/native.py, nextstrain/cli/util.py
cc @alliblk does this make things work re: #50
=> allow view to be run with --native

.readthedocs-requirements.txt, Pipfile.lock, doc/conf.py, setup.py
See preview of this PR at https://nextstrain--91.org.readthedocs.build/projects/cli/en/91/
=> Switch to our new Nextstrain theme for Sphinx

nextstrain/cli/aws/cognito/srp.py, nextstrain/cli/rst/sphinx.py, nextstrain/cli/runner/aws_batch/__init__.py, pyrightconfig.json, pytest.ini, setup.py, tests/flake8.py
See commit messages for details. If CI passes for this PR, I'll merge.
=> Fix external test breakage (round 2)

.github/workflows/ci.yaml, nextstrain/cli/command/check_setup.py, nextstrain/cli/command/version.py
See commit messages for details. Spurred by [Slack conversation](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1653075929313049).
Related to #164.
=> Report default runner

.github/actions/run-integration-tests/action.yaml, .github/actions/setup-integration-tests/action.yaml, .github/workflows/ci.yaml, .readthedocs.yml, CHANGES.md, nextstrain/cli/aws/cognito/__init__.py
=> CI build then test + refactoring

.github/actions/run-integration-tests/action.yaml, .github/actions/setup-integration-tests/action.yaml, .github/workflows/ci.yaml, CHANGES.md, nextstrain/cli/__main__.py, nextstrain/cli/rst/sphinx.py, nextstrain/cli/runner/aws_batch/__init__.py, nextstrain/cli/runner/docker.py, tests/pyright.py
Adds Windows as a platform on which we run our CI tests and fixes the issues that arise. See commit messages for details.
Related to #14 and #31.
Built on top of #180.
=> CI on Windows

CHANGES.md, doc/upgrading.rst, mypy.ini, nextstrain/cli/util.py, setup.py
=> Detect installation via Conda and other suggested upgrade command improvements

.github/workflows/ci.yaml, .github/workflows/standalone-installers.yaml, bin/standalone-installer-unix, devel/pyoxidizer, devel/release, devel/update-version, devel/venv-run
=> Shellcheck

doc/development.md, nextstrain/cli/types.py, nextstrain/cli/util.py
Small dev documentation changes. See commits.
N/A, I thought of these while reading through.
=> Minor doc fixes

nextstrain/cli/runner/conda.py
Resolves https://github.com/nextstrain/cli/issues/300
=> runner.conda: Bump Micromamba to 1.1.0

doc/development.md
Add more details to release docs from experience of CI failure during
release of 7.3.0. and the need to update bioconda-recipes for dependency
updates.
=> dev: Update release docs

doc/development.md
The config name was updated in https://github.com/nextstrain/nextstrain.org/commit/582856cdef1b07bbdaf90b5190903edbe476f79a
N/A
=> doc: Update command to retrieve NEXTSTRAIN_COGNITO_CLI_CLIENT_ID

doc/installation.rst
Leave the choice of Conda/Mamba/Micromamba open to the user.
N/A
=> doc: Simplify Bioconda installation step

.github/workflows/ci.yaml
This can be useful to have copy-able instead of looking up the command and remembering the ci-build argument.
<details>
<summary>(details)</summary>
```
--> Temporary working directory: /tmp/m2v0trm0.kg4
--> Downloading https://nextstrain.org/cli/download/ci-build/7675431145/standalone-x86_64-pc-windows-msvc.zip
--> Extracting standalone-x86_64-pc-windows-msvc.zip                                                                    
--> Removing existing /home/victor\.nextstrain\cli-standalone                                                           
--> Installing to /home/victor\.nextstrain\cli-standalone
--> Prepending /home/victor\.nextstrain\cli-standalone to PATH for current user
--> Cleaning up
Invoke-Command: The module '/home/victor' could not be loaded. For more information, run …
```
=> CI: Write installation commands to job summary

doc/commands/build.rst, doc/commands/index.rst, doc/glossary.rst, nextstrain/cli/__init__.py, nextstrain/cli/command/build.py
Good to be consistent when enumerating our runtimes, even if a couple of the lists in context suggest they're non-exhaustive.
=> Mention Singularity in a few more lists of runtimes that occur in help and docs

doc/aws-batch.md, doc/conf.py, doc/installation.rst
Adds link checking config and fixes broken links in the docs. 
Closes #388
=> Fix broken links [#388]

doc/commands/build.rst, nextstrain/cli/command/build.py
Improves rendering of reStructuredText.
N/A
=> Use :option: directive in --directory help text

doc/Makefile, doc/make.bat
Mirrors https://github.com/nextstrain/docs.nextstrain.org/pull/232
=> docs: Allow BUILDDIR to be set from environment

nextstrain/cli/net.py, nextstrain/cli/runner/conda.py
Remove rule exceptions that are no longer necessary.
- Closes #424
=> Updates for Pyright 1.1.398

nextstrain/cli/pathogens.py, nextstrain/cli/remote/__init__.py, nextstrain/cli/url.py
=> pathogens: Resolve versions via a new nextstrain.org API

CHANGES.md, doc/conf.py, nextstrain/cli/requests.py, nextstrain/cli/runner/conda.py, nextstrain/cli/util.py, setup.py
Resolves: <https://github.com/nextstrain/cli/issues/422>
Related-to: <https://github.com/nextstrain/cli/pull/379>
Related-to: <https://github.com/nextstrain/conda-base/pull/80>
=> runner.conda: Use osx-arm64 packages and support alternatives to anaconda.org

doc/aws-batch.md
I just ran through this setup guide on the Bedford lab's Hutch-managed AWS account. Some parts were confusing with the current AWS console interfaces. My guess is that some things got moved around since this guide was written. This PR updates the guide to reflect the UI that I just used.
=> Update AWS Batch docs to reflect latest AWS console interface

CHANGES.md, devel/release, doc/changes.md
Without this change, the generated commit to be pushed for release will cause CI to fail when checking that the changelog files are synced.
Closes #446
=> dev: Update MyST-formatted changelog during release

.gitignore, doc/development.md
Some small changes I thought of while running through the release process for the first time in a while (version 10.2.1.post1).
N/A
=> Update release docs

.github/actions/setup-integration-tests/action.yaml, .github/workflows/ci.yaml
CI updates to 
- remove conda `defaults` channel
- test ~source~ dist with Python 3.11 and 3.12
=> CI updates

nextstrain/cli/pathogens.py
From post-merge review of #479. Thanks, @victorlin!
=> pathogens: netrc-related 401/403 error handling polish
