nextstrain/cli

- nextstrain/cli/command/view.py
- setup.py
This lets folks run `nextstrain view` on their computer and then share
the link with others on their network.  The original motivation for this
feature is to let Ashley run Nextstrain on her computer and have her
students connect to it from their computers.  However, it's also easy to
see how it would be useful in development when working collaboratively.
The default is still local access only so that the command is secure by
default.
This adds the first external dependency to the package.  Though the
feature and dep are non-essential, I opted not to make it part of an
optional feature tag under the reasoning that "batteries included" was a
better fit for our users.  If dependencies cause installation woes down
the road, then we should reconsider that choice.
> view: Optionally allow remote network access to the webserver

- README.md
- nextstrain/cli/__init__.py
- nextstrain/cli/command/deploy.py
- nextstrain/cli/deploy/s3.py
- nextstrain/cli/util.py
- setup.py
This replaces augur/scripts/s3.py for pushing files to staging or live.
It supports arbitrary S3 buckets and automatically detects and
invalidates CloudFront distributions for those buckets.
The design of the command allows for pluggable backend modules to
support other destinations in the future (like SFTP or other cloud
hosting services).
> Add a deploy command for uploading data files

- nextstrain/cli/runner/docker.py
- nextstrain/cli/util.py
See commits for more details.  Resolves #23.
Depends on image labels added by https://github.com/nextstrain/docker-base/pull/15
> Automatically prune old images after running update

- nextstrain/cli/__init__.py
- nextstrain/cli/argparse.py
- nextstrain/cli/command/build.py
- nextstrain/cli/command/check_setup.py
- nextstrain/cli/command/deploy.py
- nextstrain/cli/command/shell.py
- nextstrain/cli/command/update.py
- nextstrain/cli/command/version.py
- nextstrain/cli/command/view.py
- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/runner/native.py
- nextstrain/cli/types.py
- nextstrain/cli/util.py
- nextstrain/cli/volume.py
This PR adds support for `nextstrain build --native …` which runs the build outside of the container image.  Support for this is on my roadmap to AWS Batch builds, but it's also nice to just provide a consistent interface for running builds under different environments.
Several related refactorings and improvements to help messaging were driven by the `--native` addition (with an eye on supporting more runners soon), and those are included as separate commits bookending `--native`.  I recommend reviewing commit-by-commit from the start rather than the PR as a whole, as the story will be clearer.
> Native runner (and changes driven by it)

- doc/aws-batch.md
- nextstrain/cli/aws.py
- nextstrain/cli/command/build.py
- nextstrain/cli/command/check_setup.py
- nextstrain/cli/config.py
- nextstrain/cli/deploy/s3.py
- nextstrain/cli/hostenv.py
- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/jobs.py
- nextstrain/cli/runner/aws_batch/logs.py
- nextstrain/cli/runner/aws_batch/s3.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/util.py
See my comments on #28 and the commit messages themselves.
> Run builds on AWS Batch [PR]

- nextstrain/cli/command/build.py
Running as `snakemake -p` causes snakemake to print shell commands run. I think this is generally useful to see what's going on and I run all local snakemake calls with `-p`.
> Run snakemake with '-p' flag to print commands

- doc/aws-batch.md
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/jobs.py
This passes `--aws-batch-cpus` and `--aws-batch-memory` to `containerOverrides`. This also moves defaults to the CLI instead of AWS config.
This has been tested and appears to work just fine.
Resolves #42.
> runner.aws_batch: Specify requested vCPU and memory

- nextstrain/cli/command/check_setup.py
- nextstrain/cli/runner/__init__.py
@alliblk When you get a a chance tomorrow, would you test out this `default-runner` branch? You should be able to run `./bin/nextstrain check-setup --set-default` and see output at the bottom like:
Setting default environment to docker
If docker support isn't found but native is, it should say "native" instead.
It'd be great to test it on the Windows machine, but one way to also test this out on your Mac is by stopping Docker using its menu in the Mac menu bar. Once a default is set, you should be able to run commands like `nextstrain build` and `nextstrain view` without specifying any runner/environment. You should also see the command's `--help` output mention which of `--docker` or `--native` is the default.
> Default environment (runner) with `check-setup --set-default`

- nextstrain/cli/hostenv.py
These environment variables are needed to access ID3C during Seattle Flu Study Augur build.
> hostenv: Include ID3C environment variables

- nextstrain/cli/__init__.py
- nextstrain/cli/argparse.py
- nextstrain/cli/command/deploy.py
- nextstrain/cli/command/remote/__init__.py
- nextstrain/cli/command/remote/delete.py
- nextstrain/cli/command/remote/download.py
- nextstrain/cli/command/remote/ls.py
- nextstrain/cli/command/remote/upload.py
- nextstrain/cli/errors.py
- nextstrain/cli/gzip.py
- nextstrain/cli/remote/s3.py
- nextstrain/cli/runner/aws_batch/s3.py
- nextstrain/cli/types.py
Adds the following commands:
nextstrain remote upload
nextstrain remote download
nextstrain remote delete (rm)
nextstrain remote list (ls)
Resolves #36. Commentary in the commit messages.
---
I know we talk about names a _lot_, but, well, names are important and tend to stick around once you use them.  Currently this PR uses _remote_. _Remote_ is our "can't think of anything else" default from discussion in #36.  It's fine, but coming from git it probably isn't intrinsically descriptive to our users.  It's a container that describes the location the contained commands act on in relative terms (in opposition to _local_).
_Files_ is another name I've been thinking of that's probably way more immediately recognizable to most people:  
nextstrain files upload
nextstrain files download …
> File management commands (upload, download, list, delete)

- nextstrain/cli/gzip.py
Depending on the data and conditions of compression, the .compress()
method will sometimes internally buffer all the data fed to it and
return only an empty byte string.  When that happened, the previous
implementation of GzipCompressingReader() mistook it as an EOF value,
stopped compression, and signaled EOF itself.  This led to some files,
but not all, being truncated during deploy/remote upload.
GzipCompressingReader() now uses its own internal buffer to make sure it
always has something to return to callers, even if multiple calls to
.compress() are necessary, thus avoiding a false EOF condition.  Support
for .read1() is dropped since it is impossible to implement its
behaviour given the API of gzip.  It was not used anyway.
Resolves #62.
> gzip: Fix bug causing the EOF value (b'') to be returned too early

- nextstrain/cli/command/check_setup.py
Change the documentation on check-setup --set-default to clarify what will happen when the flag is used.
Fixes #53   
Ran setup-checks and setup-checks -h.
> Describe how set-default chooses and env

- mypy.ini
- nextstrain/cli/runner/aws_batch/s3.py
This adds 3 retries.  I'm not sure if this is excessive, but I do see sporadic failures in uploading the zip.  The better solution is to do a multipart upload with retries (since it wouldn't need to start all over), but this should be a UX improvement.
Fixes https://github.com/nextstrain/cli/issues/75
Ran the zika tutorial
> Add retries for the S3 resource

- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/jobs.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/util.py
Job definitions are dynamically created as needed based on the base
definition specified by `--aws-batch-job`.  This is necessary to allow
runtime-configurable images since, unlike CPUs, memory, env vars, etc, a
submitted job may not directly override the container image set in the
job definition.
Resolves #57.  Implementation originally started as PR #73.
Co-authored-by: Julien BORDELLIER
> [AWS Batch] Support overriding the container image used

- .travis.yml
- Pipfile
- Pipfile.lock
- README.md
- nextstrain/cli/command/build.py
- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/runner/native.py
- nextstrain/cli/util.py
- pytest.ini
- setup.py
Limits containerized (Docker, AWS Batch) builds to the given amounts and
when applicable, informs Snakemake's resource scheduler and/or the AWS
Batch instance size selection.
Resolves #65 and #77.
---
See commit messages for more details.
> [build] Add --cpus and --memory options

- setup.py
At some point in the last few weeks, Python 3.6.1 tests on Travis CI
started reliably failing with the nested exceptions:
pkg_resources.ContextualVersionConflict: (docutils 0.16
(/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages),
Requirement.parse('docutils<0.16,>=0.10'), {'botocore'})
pkg_resources.DistributionNotFound: The 'docutils<0.16,>=0.10'
distribution was not found and is required by botocore
It appears that during install Pip ignores botocore's
docutils<0.16,>=0.10 dep in favor of recommonmark's docutils>=0.15.2
dep, and thus installs docutils 0.16.  Then, during runtime when
parse_version() is imported from pkg_resources, pkg_resources'
initialization code notices the problem and throws an exception.
I could reproduce locally by installing Python 3.6.1 with …
> Require docutils <0.16 in dev deps to avoid a version conflict

- .readthedocs-requirements.txt
- setup.py
This should speed up doc builds and let newer versions of
nextstrain-sphinx-theme be automatically used.
> Use a minimal set of deps for RTD

- nextstrain/cli/remote/s3.py
When downloading from an S3 scheme with `nextstrain remote download`,
fail more gracefully when the given URL is a directory but the recursive
option (-r) is not provided.
Resolves #93.
> s3 download: Fix usability when URL is a directory

- .travis.yml
- Pipfile.lock
- doc/development.md
- doc/installation.md
- mypy.ini
- nextstrain/cli/argparse.py
- nextstrain/cli/command/build.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/s3.py
- nextstrain/cli/util.py
- setup.py
Adds two new options to the `nextstrain build` command:
--download <pattern>
--no-download
The former may be given multiple times and specifies patterns to match against build dir files which were modified by the remote build.  The latter skips downloading results entirely, which is useful if all you care about are the logs (such as when re-attaching to a build or when a build uploads results itself elsewhere).  The default is still to download every modified file.
Currently limited to `--aws-batch` builds, as the only remote environment supported.
This functionality will particularly help the ncov build shepherds, who often have the need to download only a few files from a very large build.
Resolves #104.  See also #83.
This halves the local storage needed since no temporary file is …
> [build] Selective downloads and streaming upload/download

- .flake8
- .github/workflows/ci.yaml
- Pipfile.lock
- doc/development.md
- mypy.ini
- nextstrain/cli/argparse.py
- nextstrain/cli/authn.py
- nextstrain/cli/command/check_setup.py
- nextstrain/cli/command/login.py
- nextstrain/cli/command/remote/delete.py
- nextstrain/cli/command/remote/download.py
- nextstrain/cli/command/remote/ls.py
- nextstrain/cli/command/remote/upload.py
- nextstrain/cli/errors.py
- nextstrain/cli/gzip.py
- nextstrain/cli/remote/__init__.py
- nextstrain/cli/remote/s3.py
- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/aws_batch/logs.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/types.py
- nextstrain/cli/util.py
- nextstrain/cli/volume.py
- pyproject.toml
- pyrightconfig.json
- pytest.ini
- setup.py
- tests/pyright.py
Increases type checking coverage by
1. Using Pyright in addition to Mypy, which enables checking the interfaces of our runner and remote modules.
2. Enabling more coverage with a Mypy option.
3. Adding a few additional type annotations.
Full details in the commit messages.
Fixes #44.  
CI passes, and I've done extensive manual testing with Pyright and Mypy during development.
> Increase type checking coverage

- mypy.ini
- nextstrain/cli/command/view.py
- setup.py
Fixes #137.
Related to #31. 
I've manually tested the new `--host` functionality in all permutations of {IPv4, IPv6, hostnames, omitted} × the {native, docker} runners.
pytest passes locally.
> Drop netifaces and add --host option for view

- doc/conf.py
Avoid confusion with other CLIs now that we have a few.
> docs: Change project name from CLI → Nextstrain CLI

- doc/conf.py
This means the docs will include the specific version for "stable" on
Read the Docs with version 2022.1 or newer of nextstrain-sphinx-theme.
Also sets "release" as the Sphinx documentation says¹:
If you don’t need the separation provided between version and
release, just set them both to the same value.
¹ https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-release
> docs: Set "version" in Sphinx configuration

- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/jobs.py
Failed jobs do not have an exit code in Batch if the job failed for
infrastructural or reasons internal to AWS rather than job-specific
reasons.  For example, a job that fails because its EC2 instance is
shutdown in the middle of it will not have an exit code.
While `nextstrain build` used to exit 0 with success due to the missing
exit code, even though it correctly reported the job's failure and
failure reason.  Now it will exit 1 for a generic failure.
Tested by attaching to 3 different kinds of already done jobs we had lying around:
1. Failed job where the build workflow exited 1. `nextstrain build` exits 1, as usual.
2. Failed job where the EC2 instance it was running on was terminated unexpectedly. `nextstrain build` now exits 1 with this PR.
3. Successful job where the build …
> runner.aws_batch: Exit 1 if the job failed but there's no job exit code

- nextstrain/cli/runner/docker.py
- Improves the error handling of the check
- Supports host systems with cgroups v2
- Uses host limit even if cgroups limit isn't available
Fixes #135.
I tested using the [local VM setup I described](https://github.com/nextstrain/cli/issues/135#issuecomment-1051386199) in #135 by first reproducing the issues with nextstrain-cli 3.0.6 from PyPI and then installing this branch to see the issues resolved:
```console
$ pip3 install --user 'nextstrain-cli @ https://github.com/nextstrain/cli/archive/trs/cgroups-v2.zip'
…
$ ~/.local/bin/nextstrain check-setup
```
I also tested each commit individually to make sure they each worked as intended.
> [check-setup] Improve memory limit check

- nextstrain/cli/runner/docker.py
Further conditionalizes the use of --tty for `docker run` so that the
container process' stdout and stderr aren't merged when the user of
`nextstrain` wishes to redirect one or both of them elsewhere.
Resolves #152.
Tested with manual invocations in many permutations to ensure output remains separated. I wanted to write some Cram tests to prevent regressions, but this turns out to be difficult as Cram itself needs to redirect stdout/stderr of the test file's commands in order to do its own job. Maybe later I'll sort that out…
> runner.docker: Avoid merging stdout and stderr together

- nextstrain/cli/config.py
Locking the same file we then re-open for writing doesn't work on
Windows because the underlying LockFileEx is fd/handle-scoped not
process-scoped and a mandatory, OS enforced-lock, as documented¹:
> If the locking process opens the file a second time, it cannot access
> the specified region through this second handle until it unlocks the
> region.
The pattern works on Unix because the fcntl()-based lock isn't
mandatory.  This difference is noted in fastener's README², but I didn't
realize the full implications of Windows' mandatory lock when
introducing the locking in 821c08e.  My thinking was enforcement was
process-scoped not fd/handle-scoped.
Using a global lockfile instead of a per-file sidecar lockfile avoids
having to reason about the parent path existence checks which is a) hard …
> config: Use a global lockfile separate from the config/secrets files

- nextstrain/cli/command/view.py
- nextstrain/cli/remote/nextstrain_dot_org.py
Add "measurements" sidecar file and media type. 
I searched for "tip-frequencies" within the repo and added "measurements" to the appropriate places.
Dependent on the API update in https://github.com/nextstrain/nextstrain.org/pull/481
> Measurements sidecar

- nextstrain/cli/runner/docker.py
The fix in #153 produced a new error for me with Docker 4.5.0 on OS X 10.14.6:
```bash
$ python3 -m pip install --upgrade nextstrain-cli
$ nextstrain --version
nextstrain.cli 3.1.1
$ cat ~/.nextstrain/config
[docker]
image = nextstrain/base:build-20220215T000459Z
[core]
runner = native
$ nextstrain check-setup --set-default
nextstrain-cli is up to date!
Testing your setup…
Traceback (most recent call last):
File "/Users/jlhudd/miniconda3/envs/nextstrain/bin/nextstrain", line 8, in <module>
sys.exit(main())
File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/nextstrain/cli/__main__.py", line 10, in main
return cli.run( argv[1:] )
File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/nextstrain/cli/__init__.py", line 33, in run
return …
```
> Handle memory limits reported from Docker as floats

- nextstrain/cli/remote/s3.py
This avoids some useless work but mostly serves to head off confusion
(e.g. curl without the --compression option) and/or quirks of HTTP
clients (e.g. Snakemake's HTTP remote file provider¹) when a compressed
file is compressed again and served with a Content-Encoding: gzip
header.²
This doesn't come up with Nextstrain dataset and narrative files but
does with adjacent input files like metadata.tsv.gz and
sequences.fasta.xz which we also put in the S3 buckets (e.g.
s3://nextstrain-data/files/zika/…).³
The remote family of commands is not intended for generic S3 management
per se, but they're often useful in the Nextstrain ecosystem to manage
these ancillary data files.  Part of this is that the commands are handy
and available, part of it is that Cloudfront invalidation still remains
a …
> remote upload: Skip gzip compression for files that are already compressed

- nextstrain/cli/gzip.py
Tested manually. Dramatically improves upload speed to nextstrain.org. I performed a few ad-hoc benchmarks to ensure the compression level change was worth it.
> Improve upload speed

- nextstrain/cli/command/check_setup.py
- nextstrain/cli/config.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/runner/native.py
- nextstrain/cli/types.py
This is called when the runner is set as the default runner by
`nextstrain check-setup --set-default`.
Partially resolves <https://github.com/nextstrain/cli/issues/167>.
---
See other commit messages for more details.
Tested new setting of defaults locally. `pytest` passes locally.
> runner.docker: Set docker.image setting to the latest build-* tag by default

- nextstrain/cli/runner/docker.py
- nextstrain/cli/util.py
- setup.py
Behaviour with an implicit "latest" tag remains the same: it resolves to
the most recent "build-*" tag when `nextstrain update` is run which then
pins it in the config file.
An explicit "latest" tag used to do the same but now is preserved: it's
not updated to the most recent "build-*" tag during `nextstrain update`.
This allows folks to opt into tracking the leading edge of changes to
the image.
Resolves <https://github.com/nextstrain/cli/issues/96>.
Tested locally and works for me. Also added additional doctests.
> runner.docker: Distinguish between an explicit vs. implicit "latest" image tag when updating

- nextstrain/cli/remote/nextstrain_dot_org.py
- nextstrain/cli/remote/s3.py
The previous page recently moved and Groups doc in general was
overhauled.  Redirects are in place, so existing CLI docs pointing at
the old link still work.  This fixes newly generated CLI docs and avoids
CI errors from Sphinx warnings.
Related to https://github.com/nextstrain/docs.nextstrain.org/pull/104. Causing unrelated CI failures in #172.
Ran docs locally with warnings fatalized and all was well. Will look at CI and then merge.
> docs: Update cross-link to Nextstrain Groups explanatory documentation

- nextstrain/cli/remote/nextstrain_dot_org.py
Adds handling of particular 401 Unauthorized responses from nextstrain.org that indicate a stale or otherwise invalid token. Also reworks how auth is added to requests so it'll be easier to implement auto-renewal/retry on these failures in the future. See commit messages for details.
This is primarily a UX change in the error message presented when a `nextstrain remote` command fails because of a specific reason:
Before (generic):
```
Error: Permission denied.
Are you logged in as the correct user?  Current user: trs.
If your permissions were recently changed (e.g. new group
membership), it might help to run `nextstrain login --renew`
and then retry your command.
```
After (more specific):
```
Error: Login credentials appear to be out of date.
Please run `nextstrain login --renew` and …
```
> Handle invalid token 401 Unauthorized responses from nextstrain.org

- nextstrain/cli/runner/__init__.py
It seems better to abort early with a clear error than to continue with
a warning that's easy to miss.  Particularly so since continuing while
ignoring --image might mean distant errors quite a while later (at best)
or hard-to-detect erroneous results (at worst).
Narrows the conditional to no longer exclude invocations where --image
was given explicitly but with a value that matched the default.
> runner: Error instead of warn when --image is used with the "native" runner

- nextstrain/cli/runner/aws_batch/jobs.py
Job submissions with resourceRequirements correctly override the
defaults from job definitions that use the newer resourceRequirements
and those that use the older, deprecated vcpu and memory fields.  Job
submissions using the older fields only override job definitions that
also use the older fields; otherwise they're ignored with only an easy
to miss warning in the AWS console to alert you.
Notably, using the AWS console to modify an existing job definition
which uses vcpus and memory will switch the definition to
resourceRequirements automatically in the new revision.  This meant
revising your old job definition in the AWS console could break --cpus
and --memory for your `nextstrain build` invocations.  It also means
that --cpus and --memory would never have worked if your AWS job …
> runner.aws_batch: Use containerOverrides.resourceRequirements instead of .vcpu and .memory

- nextstrain/cli/runner/__init__.py
This can help folks who may not have a full understanding of the two
things to figure out what to do.
Related to #176.
I'll merge as soon as CI passes, but I'm happy to tweak wording with suggestions from post-merge review!
> runner: Suggest a resolution in the error message when --image is used with "native"

- .github/workflows/ci.yaml
- CHANGES.md
- pyoxidizer.bzl
Produces .tar.gz (Linux, macOS) or .zip (Windows) archives with:
1. A "nextstrain" executable containing a bundled Python interpreter +
stdlib + the Nextstrain CLI code + our dependencies.
2. External files (lib, data, etc) that are necessary but can't (for a
variety of reasons) be bundled into the executable.
These installation archives can be downloaded, extracted, and run
in-place without even a Python interpreter being installed on the host
computer, hence the "standalone" moniker.
Currently we won't distribute these with/as releases, but I'd like to
get there and this is the first step.  I think good to be producing them
in CI even now so we can make sure they continue to work and can even
use them as unofficial "daily drivers" ourselves.
Built upon #180 and #181.
> Build standalone installation archives with PyOxidizer

- .github/workflows/ci.yaml
The GitHub Actions macOS 12 image version 20220615.1 contains a
pre-installed Miniconda now.
Resolved by <https://github.com/actions/virtual-environments/issues/5623>.
> dev: Test standalone installation archive on macOS 12 in CI

- .github/workflows/ci.yaml
- devel/changes
- devel/create-github-release
- devel/release
- doc/development.md
Simplifies the local release process and builds upon other CI work to
make the dists built in CI the basis for everything downstream (tests,
standalone builds, and now PyPI too).  This also means we can include in
GitHub Releases the standalone installation archives, so they're not
squirreled away only in ephemeral Actions artifacts storage.
Real test will come with the first releases after this merges, but still, I:
> Release to PyPI and GitHub Releases from CI

- .github/workflows/ci.yaml
- CHANGES.md
- devel/read-version
- devel/release
- devel/update-version
Helps differentiate CI build artifacts from one another.
Based on #186 because of relation to release tags in CI. Related to #183 which introduced the `+git` local part.
> Include git revision in local version part of CI builds

- CHANGES.md
- nextstrain/cli/command/build.py
Applies when our own `--cpus` option isn't provided.  This will allow upgrading of Snakemake in our Docker runtime without inflicting the addition of `--cores` (or equivalent) arguments onto every existing `nextstrain build` invocation.
Snakemake requires the `--cores` option as of 5.11.¹  This has spawned much discussion² where it was made clear this is an intentional, permanent change and a default will not be added.  Add our own default instead to insulate our users from this and make Nextstrain builds fast-by-default.  Our `--cpus` option can be used to limit CPU usage back from this default if necessary, and users can always specify `--cores` (or equivalents) themselves.
Note that we don't default the `--cpus` option (opts.cpus) because we don't want to _limit_ the CPUs available in …
> build: Default Snakemake's --cores option to "all"

- nextstrain/cli/runner/aws_batch/__init__.py
Timestamps are super helpful for making sense of long-running jobs,
which are much of the use case for the AWS Batch runner.  As such, just
enable them across the board rather than making them something you opt
into (i.e. like other troubleshooting/debugging output might be).
The timestamps from AWS have millisecond-level resolution, but that
seemed a touch too fine for the longer run times we're most likely to
encounter.  Output at second-level resolution instead.
Formatted in a standard ISO 8601 format in local time (with timezone
indicated) for user friendliness.
> runner.aws_batch: Show the timestamp for each log line of the job

- bin/nextstrain
- nextstrain/cli/command/shell.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/util.py
Callers can just use `.resolve(strict = True)` now since we're >=3.6.
> Remove our resolve_path() now that we don't support Python 3.5

- CHANGES.md
- doc/upgrading.rst
- nextstrain/cli/__init__.py
- nextstrain/cli/command/debugger.py
- nextstrain/cli/util.py
- pyoxidizer.bzl
See commit messages for details, but the main change here is fixing the suggested upgrade instructions for standalone installations when a new version is detected by `nextstrain update` or `check-setup`. Probably no one but me is using the standalone installs yet so this is a minor thing… but the reason _I'm_ doing so is to notice bugs just like this. :-)
Related to #182.
> Fix suggested upgrade instructions for standalone installations

- nextstrain/cli/__init__.py
Import shadowing was happening here in the nextstrain.cli module because
of two subtly conflicting imports:
import argparse
...
from .argparse import ...
The first import binds the "argparse" symbol in nextstrain.cli to the
module from the stdlib, while the second rebinds "argparse" to the
nextstrain.cli.argparse module.¹
Later references in the same file to argparse.X worked because
nextstrain.cli.argparse happened to import (and not exclude from
re-export) the same referenced symbols.
This is confusing, so avoid it.
¹ See <https://docs.python.org/3/reference/import.html#submodules> for
why.  Note that it only applies here because nextstrain.cli is a
package with a nextstrain.cli.argparse submodule.  The same import
statements in, say, nextstrain.cli.foo wouldn't conflict.
What is the …
> dev: Avoid a confusing import binding situation

- .flake8
- nextstrain/cli/__init__.py
- nextstrain/cli/aws/cognito/__init__.py
- nextstrain/cli/command/check_setup.py
- nextstrain/cli/command/deploy.py
- nextstrain/cli/command/login.py
- nextstrain/cli/command/whoami.py
- nextstrain/cli/remote/nextstrain_dot_org.py
- nextstrain/cli/remote/s3.py
- nextstrain/cli/rst/__init__.py
- nextstrain/cli/rst/sphinx.py
- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/jobs.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/types.py
- nextstrain/cli/util.py
While looking for a flake8 check to catch import shadowing (but alas not
finding what I wanted), I realized that the whole class of "F" checks
from pyflakes are worthwhile correctness checks (in contrast to the "E"
checks, which are mostly stylistic).
Enabling all "F" checks mostly catches a slew of unused imports that
have snuck in over the years.  I would argue these are more correctness
and readability checks than style checks.
> dev: Enable a wider range of flake8 correctness checks

- CHANGES.md
- nextstrain/cli/__init__.py
- nextstrain/cli/debug.py
At the moment, this only enables printing of stack traces and the full
exception chain for handled (i.e. anticipated) errors, which otherwise
were not printed.  In the future, this mode can also control the output
of verbose debugging/troubleshooting logging for more commands.
Related to <https://github.com/nextstrain/cli/issues/201>.
> Add a debugging mode controlled by NEXTSTRAIN_DEBUG

- setup.py
> Bump nextstrain-sphinx-theme to >=2022.5

- CHANGES.md
- nextstrain/cli/remote/nextstrain_dot_org.py
A pre-action yield matches the messaging of the `remote delete` command
as of "remote delete: Update messaging to match pre-deletion behaviour"
(bb4ab4c) and the behaviour of the S3 remote as of "remote.s3: Rework
delete() to have a similar API to the other commands" (cc86a1a).
The post-action yield was an oversight and bug in the initial remote
implementation.
> remote.nextstrain_dot_org: Yield resource URL before deletion not after

- .github/workflows/ci.yaml
They're deprecated by GitHub Actions (as of ~60 days ago), are currently
undergoing scheduled brownouts, and will cease to exist ~30 days from
now.¹  We're on a train where the bridge up ahead is out, so it's time
to get off.
The build-standalone job intentionally used the oldest macOS available
for max compatibility.  While switching to macOS 11 may in theory cause
reduced portability, it also seems that PyOxidizer will by default try
to build for macOS 10.9 (for x86_64) even on newer macOS versions.²  CI
runs and testing will tell.
¹ https://github.com/actions/virtual-environments/issues/5583
² https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_distributing_macos.html#managing-portability-of-built-applications
> dev: Stop using macOS 10.15 runners in CI

- nextstrain/cli/util.py
…instead of directly linking to github.com.  This indirection is better
branding, but more importantly gives us the ability to use
nextstrain.org to insulate users of older CLI versions from future
changes to where the archives actually live.
See also <https://github.com/nextstrain/nextstrain.org/pull/578>.
> Use nextstrain.org for standalone installation archive URLs

- CHANGES.md
- nextstrain/cli/command/remote/download.py
- nextstrain/cli/remote/nextstrain_dot_org.py
Includes all of the resource path except for the leading namespace part
(if any), e.g. /groups/X or /staging.
This reduces the potential for ambiguous filenames and makes it easier
to copy datasets/narratives between destinations (e.g. from one group to
another) while retaining the same path.  It is, however, a
**potentially-breaking change** if you're relying on the filenames of
the downloaded datasets/narratives (e.g. for automation).
Related to #169.
> remote download: Use more of the resource path in the local filename

- CHANGES.md
- nextstrain/cli/command/build.py
- nextstrain/cli/runner/aws_batch/s3.py
This helps reduce the number of patterns needed to download
large-but-specific subsets of a build with many output files (e.g.
ncov).
Resolves <https://github.com/nextstrain/cli/issues/123>.
> build: Support advanced globbing features in --download patterns

- .github/workflows/standalone-installers.yaml
- CHANGES.md
- bin/standalone-installer-unix
- bin/standalone-installer-windows
- nextstrain/cli/__init__.py
- nextstrain/cli/command/init_shell.py
- nextstrain/cli/command/remote/__init__.py
- nextstrain/cli/util.py
Shell programs to download and unpack the standalone installation archives into standard locations, potentially upgrading/overwriting a prior standalone install.
These programs will be served from GitHub directly out of this repo via convenience redirects on nextstrain.org.
Related-to: <https://github.com/nextstrain/nextstrain.org/pull/582>
Related-to: <https://github.com/nextstrain/docs.nextstrain.org/pull/123>
> Standalone archive installers

- CHANGES.md
- nextstrain/cli/runner/docker.py
Downloads the image if it's not already available locally, avoiding an awkward download on first use.  It makes more sense to do this in `setup` than to advise folks to run `update` after install.  The update machinery is still used behind the scenes.
Diff best viewed with whitespace ignored.
> runner.docker: Initial, minimal `setup` support

- .github/actions/run-integration-tests/action.yaml
- .github/actions/setup-integration-tests/action.yaml
- CHANGES.md
- doc/aws-batch.md
- doc/installation.md
- nextstrain/cli/argparse.py
- nextstrain/cli/command/build.py
- nextstrain/cli/command/check_setup.py
- nextstrain/cli/command/setup.py
- nextstrain/cli/command/shell.py
- nextstrain/cli/command/update.py
- nextstrain/cli/command/view.py
- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/ambient.py
- nextstrain/cli/runner/conda.py
- nextstrain/cli/util.py
> Rename "native" runtime/runner to "ambient"

- .github/actions/run-integration-tests/action.yaml
- CHANGES.md
- nextstrain/cli/runner/conda.py
Splits up the big initial command block to setup runtimes into single-command steps so we can condition runtime setup on host OS support (instead of trying setup on all OSes and ignoring errors).
Based on #222, because `nextstrain setup docker` is handy there.
> Add Conda runtime to our CI integration tests

- CHANGES.md
- nextstrain/cli/runner/conda.py
See commit messages. Main change is in the title.
Related to <https://github.com/nextstrain/conda-base/pull/1>.
> Use our new nextstrain-base Conda meta-package

- CHANGES.md
- doc/commands/authorization.rst
- doc/index.rst
- nextstrain/cli/__init__.py
- nextstrain/cli/command/authorization.py
> Add an `authorization` command to ease direct requests to nextstrain.org's web API

- CHANGES.md
- nextstrain/cli/command/shell.py
Resolves <https://github.com/nextstrain/cli/issues/231>.
> shell: Ensure the history file always exists

- CHANGES.md
- nextstrain/cli/runner/conda.py
It'll be good to be using a 1.0 release!
> runner.conda: Bump Micromamba version from 0.27.0 to 1.0.0

- .flake8
- nextstrain/cli/runner/aws_batch/logs.py
Fixes syntax of the flake8 config file.
The trailing comments were apparently bogus this whole time!  The
configuration documentation does mention this¹, though not sure it did
at the time I wrote the config initially.  In any case: oops.
flake8 version 6.0.0, released earlier today, started validating the
config and thus detecting the erroneous entries, which made our CI start
to fail with:
ValueError: Error code '#' supplied to 'extend-ignore' option does
not match '^[A-Z]{1,3}[0-9]{0,3}$'
Failures were limited to Python ≥3.8, as flake8 6.0.0 bumped its minimum
Python dep, so older Python versions kept using older flake8 versions,
but the syntax error affected them nevertheless.
¹ https://flake8.pycqa.org/en/latest/user/configuration.html
CI failures [noticed in an unrelated …
> Fix CI (again)

- nextstrain/cli/remote/nextstrain_dot_org.py
This helps in particular with user-caused bad requests, such as trying to upload to dataset URLs which include underscores instead of slashes. It will also let us use 400 responses more widely on the server side since we know the CLI user will now see the error message.
Related-to: https://github.com/nextstrain/nextstrain.org/pull/611
Example of the error message:
```
$ NEXTSTRAIN_DOT_ORG=http://localhost:5000 nextstrain remote upload groups/test/foo_bar foo_bar
.json
Uploading foo_bar.json as http://localhost:5000/groups/test/foo_bar
Error: The remote server rejected our request:
Resource (e.g. dataset and narrative) paths may not include
underscores (_); use slashes (/) instead
This may indicate a problem that's fixable by you, or it
may be a bug somewhere that needs to be fixed by the …
```
> remote.nextstrain_dot_org: Handle 400 Bad Request errors

- CHANGES.md
- nextstrain/cli/command/view.py
See commit messages for details. The summaries:
1. 6950f2f view: Support narratives
2. 334ab6d view: Open a browser automatically
3. 77f2975 view: Adjust dataset_paths() and narrative_paths() to take a list of file paths
4. de0ef0c view: Accept paths to a specific dataset or narrative file
#128
> view: Support narratives

- .github/workflows/ci.yaml
- .gitignore
- CHANGES.md
- devel/pyoxidizer
- devel/within-container
Improves our support of even older glibc and distro versions:
```diff
--- before
+++ after
@@ -27,24 +27,24 @@ libutil.so.1
Symbol Versioning
=================
gcc
-----
Minimum Version: 4.2.0
Minimum Distro Versions:
Debian 7
Fedora 16
OpenSUSE 11.4
RHEL 6
Ubuntu 12.04
glibc
-----
-Minimum Version: 2.27
+Minimum Version: 2.17
Minimum Distro Versions:
-  Debian 10
-  Fedora 28
-  No known OpenSUSE versions supported
-  RHEL 8
-  Ubuntu 18.04
+  Debian 8
+  Fedora 19
+  OpenSUSE 12.3
+  RHEL 7
+  Ubuntu 14.04
```
- #234 
- CDC's issues with CentOS 7
> Support older glibc versions (e.g. CentOS 7) for standalone installations

- CHANGES.md
- nextstrain/cli/command/view.py
- setup.py
- tests/open_browser.py
Long story short, the multiprocess "spawn" start method doesn't (and maybe can't) work for our standalone executable on Unix systems, so we can't use it unconditionally to avoid bugs arising from "fork" vs. "spawn" on different platforms.  See the bug this resolves (below) for all the details.
Instead, use the default platform-dependent start method and try to catch future bugs with tests that exercise open_browser() under both "fork" and "spawn".
Resolves <https://github.com/nextstrain/cli/issues/242>.
> view: Fix --open so it works when using our standalone executable

- CHANGES.md
- nextstrain/cli/aws/cognito/__init__.py
Version 39 changed the wording of the deprecation warning added by version 37.  39 still works on Python 3.6 but now warns that version 40 will be the last to include support.  Without supression, the deprecation causes loud, user-visible warnings when running any command:
Python 3.6 is no longer supported by the Python core team. Therefore,
support for it is deprecated in cryptography. The next release of
cryptography (40.0) will be the last to support Python 3.6.
This is more reason to drop 3.6 ourselves eventually as we'll not want to be using an older and older cryptography release.  In the meantime, however, squash the warning since it does no good for end users.
Resolves <https://github.com/nextstrain/cli/issues/245>.
> Suppress new warning from cryptography 39 about deprecated Python 3.6 support

- .github/actions/setup-integration-tests/action.yaml
Adapted from https://github.com/nextstrain/augur/pull/1126.
> Improve usage of setup-miniconda

- .github/actions/run-integration-tests/action.yaml
- .github/actions/setup-integration-tests/action.yaml
- CHANGES.md
- doc/aws-batch.md
- doc/installation.rst
- nextstrain/cli/argparse.py
- nextstrain/cli/command/check_setup.py
- nextstrain/cli/command/shell.py
- nextstrain/cli/command/update.py
- nextstrain/cli/command/view.py
- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/runner/singularity.py
- nextstrain/cli/util.py
Add a new runner for a Singularity runtime based on the Docker runtime
It's been my intention to support Singularity since day 1, but I never got around to implementing it because usage seemed little to non-existent amongst Nextstrain users I knew about.  (Though maybe that's a chicken-or-the-egg problem!)  We've since had users report their ad-hoc use of Singularity with Nextstrain, however, and Singularity is often the only containerization method supported by HPC systems.  So it seems important to support.
Resolves <https://github.com/nextstrain/cli/issues/2>.
You can test this yourself using a source checkout of this PR, or with the standalone build produced by this PR:
```
curl -fsSL --proto '=https' https://nextstrain.org/cli/installer/linux \
| DESTINATION=/tmp/cli-test bash -s …
```
> Singularity runtime

- bin/standalone-installer-unix
The previous check worked only on macOS 12 and 13, because the executable path on macOS 11 is:
/Library/Apple/usr/libexec/oah/oahd
On all macOS versions, however, the process runs as the _oahd user.  In case the _oahd user doesn't exist, direct stderr to the bit bucket to avoid a noisy error being confusing to the person running the installer.
Troubleshooting happened on Slack¹ with the help of @cassiawag and @corneliusroemer.
¹ <https://bedfordlab.slack.com/archives/C0K3GS3J8/p1675714639052449>
> standalone-installer-unix: Check for Rosetta 2 in a way that works on macOS 11 too

- .github/workflows/ci.yaml
Changes to external dependencies, like new releases of Python packages, are a common source of build breakage.¹  Ensure we know sooner than later when they break our build by running CI every day.
¹ The latest example is <https://github.com/nextstrain/cli/pull/257>.
> dev: Run CI every day on a schedule to catch external breaking changes

- setup.py
mypy 0.971 is the last version to support Python 3.6, so this is what pip installs on 3.6.
types-requests 2.28.11.12 is the last version to support mypy <1.0.0, due to changes in how the "Self" type is handled.¹  However, there's no way to declare that in package metadata (without requiring mypy, which is inappropriate for a typeshed package), so we have to resolve this dependency ourselves.²
With a too-new types-requests, mypy fails on 3.6 with errors like:
nextstrain/cli/remote/nextstrain_dot_org.py:230: error: Self? has no attribute "auth"
which we saw in CI failures.³
We'll drop support for Python 3.6 sooner than later, but for now, keep it going.
¹ <https://github.com/python/typeshed/commit/7180d0223b3cfb0275bdc4dff902439536dd4e3d>
<https://github.com/python/typeshed/pull/9702>
² It …
> dev: Pin types-requests on Python 3.6 to a version that works with mypy on 3.6

- CHANGES.md
- nextstrain/cli/remote/nextstrain_dot_org.py
When an unknown file was given for upload, the error message incorrectly included the literal string "{files}" instead of replacing it with the actual list of files.
Although this string doesn't need to be an f-string, the other similar error messages below it do, and preserving the parallel construction of the error messages is helpful for readability.
https://support.nextstrain.org/agent/nextstrain/nextstrain/tickets/details/668036000003639001
> remote.nextstrain_dot_org: Fix uninterpolated placeholder in error message

- CHANGES.md
- nextstrain/cli/command/build.py
- nextstrain/cli/runner/aws_batch/__init__.py
> [batch] Improvements when attaching to completed jobs

- CHANGES.md
- nextstrain/cli/argparse.py
The section heading used in argparse's formatted help output changed in 3.10¹, rendering --help equivalent to --help-all.  This affected anyone with Nextstrain CLI installed on Python 3.10 or newer, including our standalone installation binaries.
¹ <https://github.com/python/cpython/pull/23858>
<https://bugs.python.org/issue9694>
> argparse: Restore --help and --help-all difference on Python ≥3.10

- CHANGES.md
- nextstrain/cli/runner/aws_batch/jobs.py
> botocore 1.28.0 compat

- bin/standalone-installer-unix
- nextstrain/cli/command/init_shell.py
In Bash prior to 4.0 (released in 2009), the `source` builtin does not properly read input from a pipe, named or otherwise.  When given a pipe, such as via process substitution (i.e. `<(…)`), it silently does nothing and exits 0.  This can cause a SIGPIPE in the process on other end of the pipe and, in Python, a BrokenPipeError.
Unfortunately, macOS ships with Bash 3.2.57 (released in 2007) and, for legal reasons, is unlikely to ever be upgraded.  Switching to `eval` with command substitution (i.e. `$(…)`) avoids the issue for Bash users on macOS and results in no functional change for everyone else.
We _will_ have to ensure that the output of `nextstrain init-shell` remains below command line length limits since the output is now interpolated into the command line, but I don't think this …
> standalone-installer-unix: Use `eval` instead of `source` to avoid issues on old versions of Bash

- bin/standalone-installer-windows
It is not uncommon for user home directories to have spaces, and Invoke-Expression [does not work well](https://devblogs.microsoft.com/powershell/invoke-expression-considered-harmful/) with paths that have spaces. The call operator is more suitable for this use case.
Quoting updated to reflect [call operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.3#call-operator-) [syntax](https://ss64.com/ps/call.html).
Fixes #276
> standalone-installer-windows: Use call operator (&) instead of Invoke-Expression

- bin/standalone-installer-unix
Previously, the command could result in unexpected errors if the shell init file did not end with a newline (for reasons beyond our control).
If the file already ends with a newline, this comes with the added benefit of using whitespace to distinguish the "scope" of this command as separate from whatever was there before.
I noticed this because my own `.zshrc` file did not end with a newline and I got this error upon opening new sessions after running the command:
```
/Users/vlin/.zshrc:63: parse error near `\n'
```
which made sense after inspecting the file contents:
```
function some-function()
{
…
}eval "$("/Users/vlin/.nextstrain/cli-standalone/nextstrain" init-shell zsh)"
```
> Add newline before eval command

- nextstrain/cli/runner/aws_batch/s3.py
Fix Pyright errors that have been raised in our scheduled CI runs since the release of Pyright 1.1.306.¹ I have not dug into the Pyright changelog to determine the exact change that leads to this new error.
¹ https://github.com/nextstrain/cli/actions/runs/4874920417
> Fix Pyright errors

- nextstrain/cli/runner/conda.py
Learned through the conda-base repo's CI job that Anaconda's `/release/{owner_login}/{package_name}/latest` API endpoint returns the latest package version regardless of labels.¹ This means that users can accidentally install test versions of the nextstrain-base package.
I tried various endpoints from the API docs² to see if we can pass the label as a URL param that can allow the filtering to be done on server, but there were no leads in the docs and nothing I tried worked. So this commit adds an explicit check for the latest `main` version by pulling all package files and then filtering for the label and finding the max `upload_time`.
¹ https://github.com/nextstrain/conda-base/issues/26 ² https://api.anaconda.org/docs
> runner.conda: Explicitly get latest `main` version

- CHANGES.md
- doc/installation.rst
- nextstrain/cli/command/shell.py
- nextstrain/cli/debug.py
- nextstrain/cli/remote/s3.py
- nextstrain/cli/runner/singularity.py
- nextstrain/cli/util.py
- setup.py
Resolves https://github.com/nextstrain/cli/issues/274.
> Singularity compatibility fixes

- nextstrain/cli/runner/conda.py
Our nextstrain-base Conda package versions are not PEP-440 compliant, so we inadvertently relied on packaging.version.parse_version() falling back to its LegacyVersion class when it encountered an InvalidVersion error.  LegacyVersion was dropped, however, in packaging 22.0 (December 2022).¹  This resulted in seeing the InvalidVersion error during runtime update, e.g.:
packaging.version.InvalidVersion: Invalid version: '20221019T172207Z'
To avoid that, we start handling InvalidVersion ourselves and produce a valid proxy version instead with reasonable comparison semantics similar to LegacyVersion.
The new version handling is more than strictly necessary for our current package versions (which could just be simpler string comparisons), but it allows us more leeway to change package …
> runner.conda: Explicitly handle our package versions which are invalid by PEP-440

- .github/workflows/ci.yaml
- devel/pytest
- doc/development.md
- nextstrain/cli/rst/__init__.py
- setup.py
This reverts commit d2463b72c153ea6720d920baff01003d51ec4c04.
Pip's dependency resolution around docutils no longer appears to be an issue.  We also no longer test on Python 3.6.1 in CI but instead use 3.6.15.
This pin was causing issues in CI tests itself since it was preventing use of newer docutils with fixes for deprecated pkg_resource APIs.  The older docutils versions caused warnings at test time.
Since docutils is also a non-dev dependency and unpinned there, it's also nice to use the same version in dev/test as in non-dev installs.
> Revert "Require docutils <0.16 in dev deps to avoid a version conflict"

- .github/workflows/ci.yaml
The change from `pytest` to `./devel/pytest` in "dev: Set
NEXTSTRAIN_RST_STRICT=1 when running tests" (dc21d8d) caused pytest to
stop running entirely on our Windows jobs but not exit with an error
either.  The default shell there is pwsh (PowerShell) and it silently
(?!) fails to execute the Bash program, maybe because pwsh on Windows
doesn't support shebangs?
Explicitly use bash as the default shell for test-source jobs, similar
to the default we set for other jobs in this workflow.  This covers all
steps in the job.  Even though the "Install Nextstrain CLI" step works
on pwsh now, this guards against future modifications breaking it like I
inadvertently did with the pytest step.
Related-to: <https://github.com/nextstrain/cli/pull/287>
> ci: Fix silent failure to run pytest on Windows

- nextstrain/cli/runner/docker.py
The previous forms relied on defaults and outdated behaviour.  They predate the change to single-runtime application of `nextstrain update` from its previous application to "all runtimes, but in practice only Docker".  The more precise forms will be correct, for example, even if the Docker runtime isn't the default.
> runner.docker: Use more precise example commands in check-setup failure messages

- CHANGES.md
- nextstrain/cli/command/view.py
A big improvement over simply pausing for 2s before opening it and hoping for the best.
> view: Wait for Auspice to start responding before opening the browser

- CHANGES.md
- LICENSE.id3c
- devel/pytest
- devel/setup-venv
- devel/venv-run
- nextstrain/cli/argparse.py
- nextstrain/cli/command/view.py
- nextstrain/cli/env.py
- nextstrain/cli/runner/__init__.py
- nextstrain/cli/runner/ambient.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/jobs.py
- nextstrain/cli/runner/aws_batch/s3.py
- nextstrain/cli/runner/conda.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/runner/singularity.py
- nextstrain/cli/types.py
- nextstrain/cli/util.py
Other context in my notes:
- [26 Aug 2022](https://github.com/tsibley/blab-standup/blob/master/2022-08-26.md#26-august-2022)
- [2 June 2023](https://github.com/tsibley/blab-standup/blob/master/2023-06-02.md#2-june-2023)
> Environment variables

- .github/workflows/ci.yaml
I was hopeful that actions/setup-python would fix this sooner than later and we could just wait for the upstream fix… but that hasn't happened and now I want to cut a release (which requires working CI), so a workaround it is.
> dev: Work around issue in CI with Python 3.7.17 on macOS

- .github/workflows/ci.yaml
This is already used by other repos. It builds the docs with the flags used previously plus an additional flag -n to warn on missing references¹.
¹ https://github.com/nextstrain/.github/blob/cc6f4385a45bd6ed114ab4840416fd90cc46cd1b/.github/workflows/docs-ci.yaml#L43-L48C33
N/A
> Use central reusable workflow for building docs

- .github/actions/setup-integration-tests/action.yaml
This should fix our CI.
The initial Bioconda builds (build number 0) for Snakemake 7.30.2 missed a major bump in Snakemake's minimum Python version (3.7 → 3.9).  This rendered the Bioconda packages for snakemake and snakemake-minimal installable on 3.7 or 3.8 but non-functional at runtime.  Subsequent builds (build number 1 and onwards) of 7.30.2 fixed this oversight, but since the initial builds haven't been yanked/marked broken, the solver still chooses them.¹
Since Conda's package spec syntax doesn't allow for exclusion of specific builds, exclude all of 7.30.2.  It's fine if we never test on this patch version²; Python 3.6–3.8 will get <7.30.2 and 3.9 and onwards will get the already-available subsequent version 7.31.0.
¹ <https://github.com/bioconda/bioconda-recipes/pull/42147>
² It …
> dev: Exclude Snakemake 7.30.2 when installing from Bioconda for ambient runtime setup

- CHANGES.md
- doc/commands/build.rst
- nextstrain/cli/__init__.py
- nextstrain/cli/argparse.py
- nextstrain/cli/command/build.py
- nextstrain/cli/errors.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/volume.py
Make the `nextstrain build` pathogen `<directory>` optional when `--attach` + `--no-download` are used
This allows usages which just want to check job status/logs to stop    passing in a meaningless/unused directory.
> No download? No build dir? No problem!

- nextstrain/cli/runner/__init__.py
- nextstrain/cli/types.py
Two related commits:
----
**dev: Fix new errors in type checking around the type of Ellipsis (...)**
pyright 1.1.325 (released yesterday) added support for @type_check_only decorators¹, which were added (a year ago) to the builtins.ellipsis type of the stdlib typeshed².  This type is available only during type-checking and doesn't actually exist at runtime, but previously pyright didn't care about that (and mypy still doesn't).  Now it does, noticed thanks to scheduled CI, and throws an error like:
"ellipsis" is marked as @type_check_only and can be used only in
type annotations (reportGeneralTypeIssues)
Explicitly clarify to pyright that our variable is a type alias³ and not a value also used at runtime so it knows its ok to use the type of Ellipsis (via a forward reference to the …
> Ellipsis type; fix broken CI

- CHANGES.md
- doc/commands/view.rst
- nextstrain/cli/command/view.py
These are widely-used conventions, and also Auspice recommends setting PORT when it runs into a "port in use" error trying to bind at start up. It's good to make that suggestion work thru `nextstrain view`.
Reported by @corneliusroemer in Slack.¹
¹ <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1694718932379359>
> view: Respect HOST and PORT as defaults for --host and --port

- nextstrain/cli/runner/conda.py
This our intent and expectation, and it's good to be explicit about it. It may surface more installation issues, such as the one we observed in monkeypox CI¹ with the latest version not being installable, but obscuring those or surfacing them later on is _probably_ worse than addressing them head on earlier.  This change will mean that any macOS 10.14 users, if any, would have to use
NEXTSTRAIN_CONDA_BASE_PACKAGE="nextstrain-base ==20230615T171309Z"
since newer versions aren't installable for them.²
This behaviour also parallels update's behaviour since "runner.conda: Explicitly specify a nextstrain-base version when updating" (d6e4f2b). It was an oversight (on my part) to not use the same behaviour during setup, but at the time I was focused on fixing an update bug.
Related-to: …
> runner.conda: Explicitly install the latest package version during setup

- CHANGES.md
- setup.py
Changes to the `auto_mkdir` parameter in https://github.com/fsspec/filesystem_spec/pull/1358 leads to the error described in https://github.com/fsspec/s3fs/issues/790.
Upstream fixes to come soon via https://github.com/fsspec/filesystem_spec/pull/1365 but good to avoid versions that we know are broken.
> Avoid fsspec/s3fs 2023.9.1 due to errors caused by `auto_mkdir`

- .github/actions/setup-integration-tests/action.yaml
The release of SingularityCE 4.0.0 a few hours ago¹ caused a failure during CI for the release of Nextstrain CLI 7.3.0.²  We got unlucky as that release's CI was the first to encounter the issue due to timing. We can test the compatibility of SingularityCE 4.x with both our CI setup process and Singularity runtime at some later point.
¹ <https://github.com/sylabs/singularity/releases/tag/v4.0.0>
² <https://github.com/nextstrain/cli/actions/runs/6238951959>
> dev: Test against the SingularityCE 3.x series in CI

- CHANGES.md
- nextstrain/cli/runner/conda.py
By default Python will search for modules in the user site directory, e.g. ~/.local/lib/python3.10/site-packages/.  This is an isolation leak that can cause conflicts with our Conda runtime since its not containerized, and we observed such an issue during a workshop.  Plug that leak by both disabling the searching of a user site directory entirely (the proximate issue) and pointing the whole Python user base directory to an alternate location (a preventative measure against other user base directory usages).
Similarly, PYTHONPATH and (probably more rarely) PYTHONHOME also have the potential to cause similar issues, so we now ensure they're unset when entering our Conda runtime.  I reviewed other environment variables used by Python¹ and they seem reasonable to leave as-is (at least at …
> runner.conda: Plug isolation leaks related to Python

- CHANGES.md
- doc/commands/build.rst
- nextstrain/cli/command/build.py
- nextstrain/cli/rst/__init__.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/jobs.py
See commit messages for details, and also the [new changelog entries](https://github.com/nextstrain/cli/pull/308/commits/e3888cd527b694ca619443943c01f66696982a01).
This work is motivated by deeper integration for GitHub Actions workflows that launch builds as AWS Batch jobs.
> AWS Batch job control

- setup.py
Version 1.6 released this morning dropped support for targeting Python 3.6, and also introduced other type checking issues, breaking CI.  While we'll also drop Python 3.6 soon¹, we haven't yet.  We may also drop Mypy² sooner than later and just use Pyright², but again, we haven't yet.
Resolves <https://github.com/nextstrain/cli/issues/320>.
¹ <https://github.com/nextstrain/cli/issues/136#issuecomment-1622294693>
² <https://github.com/nextstrain/cli/issues/320#issuecomment-1756429861>
> dev: Require Mypy <1.6

- nextstrain/cli/authn.py
In this case, the "cognito:groups" claim does not exist. Previously, this resulted in a KeyError upon login and whoami commands.
N/A
> authn: Handle case when a user is not in any group

- bin/standalone-installer-unix
We were suggesting nonsense (~/.shrc) due to our final fallback/guess. Instead, handle sh specifically and correctly.
Resolves <https://github.com/nextstrain/cli/issues/319>.
> standalone-installer-unix: Use ~/.profile when the default shell is sh

- nextstrain/cli/remote/nextstrain_dot_org.py
2 weeks ago¹, Pyright on 3.10 CI started failing with an error:
"status_code" is not a known member of "None"
I looked at the requests source code² and it makes sense. However, I was not able to reproduce the CI error locally and don't understand why it only happens on 3.10. Hopefully this addresses the issue.
¹ https://github.com/nextstrain/cli/actions/runs/6605300519/job/17940321340#step:5:88
² https://github.com/psf/requests/blob/839a8edec37c81a18ac8332cfbd44f44e1ae6206/src/requests/exceptions.py#L19
> Cast err.response to Response class for Pyright

- nextstrain/cli/remote/s3.py
Allows us to skip gzip compression when uploading .zst files. Includes adding ".zst" to the mimetypes encoding types dictionary because it is not yet included in the standard library.¹
¹ https://github.com/python/cpython/blob/2ef3676a5bb8fba531fb8237ce50c27ebe37fb96/Lib/mimetypes.py#L411-L417
> remote: Add zstd to encoding types

- .github/workflows/ci.yaml
- CHANGES.md
- doc/development.md
- doc/installation.rst
- mypy.ini
- nextstrain/cli/__main__.py
- nextstrain/cli/aws/cognito/__init__.py
- nextstrain/cli/command/build.py
- nextstrain/cli/util.py
- pyrightconfig.json
- setup.py
Drop support for Python 3.6 and 3.7. Adding support for newer versions will be done in separate PRs.
- Closes #136
- Previous attempt at #256
> Bump minimum Python version to 3.8

- .github/workflows/ci.yaml
- CHANGES.md
- nextstrain/cli/resources/__init__.py
- setup.py
Add the PyPI Trove classifier, test in CI, and address CI errors.
- (not strictly necessary) Based on #325
- https://github.com/nextstrain/augur/issues/1334
> Explicitly support Python 3.11

- nextstrain/cli/argparse.py
The latest version of Pyright exposed a new error for this project:
argparse.py:52:9 - error: Method "_fill_text" overrides class "HelpFormatter" in an incompatible manner
Parameter 4 name mismatch: base parameter is named "indent", override parameter is named "prefix" (reportIncompatibleMethodOverride)
I don't think the issue resulted in badly rendered docs, but nevertheless it's easy to address this by changing a couple names.
Fixes the issue that caused [today's scheduled CI](https://github.com/nextstrain/cli/actions/runs/7118237967) to fail.
> Address new Pyright error

- nextstrain/cli/remote/nextstrain_dot_org.py
See commit message.
[CI failing](https://github.com/nextstrain/cli/actions/runs/7265991739)
> Fix failing Pyright test

- nextstrain/cli/remote/s3.py
Previously, other reasons detailed in the changes would show an error message saying "no bucket exists" even if it does exist.
Update the error text to describe more possible reasons based on docs for S3.Client.head_bucket.¹ and local testing. This list might not be exhaustive, but I can't come up with any other scenarios.
¹ <https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/head_bucket.html>
- [Internal inquiry](https://bedfordlab.slack.com/archives/C036L7V615F/p1703710506208669)
- Closes #56
> remote: Show more possible reasons for S3 access error

- devel/generate-command-doc
- nextstrain/cli/__init__.py
- nextstrain/cli/aws/cognito/__init__.py
- nextstrain/cli/browser.py
- nextstrain/cli/command/__init__.py
- nextstrain/cli/command/view.py
- nextstrain/cli/remote/nextstrain_dot_org.py
- nextstrain/cli/remote/s3.py
See commit messages. Done during work on the path towards OIDC/OAuth2-based login, but suitable for separate review and independent merge.
> Various and sundry

- nextstrain/cli/command/view.py
A slice like x[0:2] may evaluate to ('a',) or ('a', 'b',) depending on the length of x.  Pyright changed its checking of this slice behaviour for tuples in 1.1.345 (released 4 days ago)¹, which started raising issues with this code in CI.
While we humans know that the sockaddr tuples here always have at least two elements, Pyright does not.  I think Pyright could do better here as it knows the type of sockaddr is
Tuple[str, int] | Tuple[str, int, int, int]
and thus I think should be able to know for sure the type of a 0:2 slice.  Instead, it evaluates the slice type to an ambiguous
Tuple[str | int, ...]
which is incompatible with our declared return type.
I went to report this behaviour regression, but someone's already beat me to it.²
¹ …
> dev: Appease Pyright 1.1.345's changed type checking of tuple slices

- CHANGES.md
- nextstrain/cli/runner/singularity.py
My intent was (and remains) to try to maintain compatibility with both SingularityCE and Apptainer after the Singularity fork.  I didn't realize/recall that Apptainer restarted version numbering when I added this version inspection!
It would be most ideal if Apptainer's `singularity` executable reported the equivalent/compatible SingularityCE version, but that's understandably difficult and so I get why it reports the Apptainer version instead.
Thanks to @osageorange for raising this issue, testing this patch, and reporting back that it works!
As SingularityCE and Apptainer continue to diverge, a more complicated treatment of them may be needed, but for now this should suffice.
Resolves <https://github.com/nextstrain/cli/issues/329>.
> runner.singularity: Explicitly support Apptainer's `singularity` when checking versions

- CHANGES.md
- nextstrain/cli/remote/nextstrain_dot_org.py
(Based upon #333 for less in-flight conflict.)
> Supporting downloading datasets not in manifest

- devel/create-github-release
- devel/reflow-markdown
This is necessary to work around GitHub's rendering of release notes which treats newlines in the Markdown as hard line breaks instead of soft line breaks (which is more standard).  GitHub itself isn't consistent and treats newlines as hard or soft in different places.¹
This has bugged me for a while, and I've always resorted to hand-correcting the release notes after the release is created.  But that's annoying and means that the crappy formatting still appears in emails and other notifications triggered by the release creation event. I'll be glad to have Pandoc doing this for me instead!  It hadn't occurred to me to use Pandoc for this until now.
¹ <https://github.com/orgs/community/discussions/57633>
> devel/create-github-release: Reflow paragraphs in changelog Markdown to single long lines

- CHANGES.md
- nextstrain/cli/authn/__init__.py
- nextstrain/cli/authn/configuration.py
See commits. Addresses review feedback for #333.
> Review feedback: Support other nextstrain.org-like remotes

- CHANGES.md
- devel/release
- nextstrain/cli/command/build.py
- nextstrain/cli/command/shell.py
- nextstrain/cli/runner/aws_batch/__init__.py
Mirrors the existing behaviour of `nextstrain shell`, introduced by "shell: Add support for the managed Conda runtime" (6e2d73d).  It was an oversight to not do the same for `nextstrain build` at the same time.
----
Two other smaller changes too; see their commit messages.
> build: Error if overlays are given for a runtime other than Docker or Singularity

- .github/workflows/ci.yaml
- CHANGES.md
GitHub released public runners.¹  Great timing too, as I was just about
to look into using the ARM hardware that's available for macOS with
GitHub's (paid) large runners².  This also beats operating a self-hosted
runner, whether that's on EC2³ or our own Mac Mini.⁴
And the icing on the cake is that everything Just Worked by merely
enabling builds for this architecture.  \o/  High fives all around,
everyone.
Changes to the standalone installer to follow separately⁵, as those need
to be held for merge until after the first release with these builds
available.
¹ <https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/>
² <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1706556690621389>
³ …
> Standalone builds for macOS aarch64 (aka arm64, Apple Silicon, M1/M2)

- CHANGES.md
- nextstrain/cli/command/build.py
- nextstrain/cli/command/shell.py
- nextstrain/cli/runner/aws_batch/__init__.py
…as this is the direction we're moving.
The main change is making the filesystem isolation boundary (i.e. what's mapped to `/nextstrain/build` in a container) a _separate thing_ from the workflow and initial working directory (i.e. what's given to `nextstrain build`).  In this codebase, these two things are referred to as the _build volume_ (aka `opts.build`) and the _working volume_. Historically, the working volume given to the runners for `nextstrain build` and `nextstrain shell` _was_ the build volume; now, they're separately considered and sometimes differ.
See the included changelog entry for usage details and rationale.  For background, I made the initial proposal for this feature¹ on a PR in our pathogen-repo-template repository and some discussion ensued.
¹ …
> Better support pathogen repositories which place workflows in subdirectories

- CHANGES.md
- nextstrain/cli/runner/conda.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/util.py
When on macOS on aarch64 hardware, the Conda runtime currently requires Rosetta.  The Docker runtime does not require it, but can benefit from it because our aarch64 image isn't totally free of x86_64 code (yet?), so emulation is required and Rosetta is faster than QEMU.
The standalone installer still checks for Rosetta as we previously didn't produce aarch64 standalone binaries¹, but that check will be made conditional on Nextstrain CLI version in a subsequent commit² after the first release of aarch64 support and these new Rosetta checks.
¹ <https://github.com/nextstrain/cli/pull/357>
² <https://github.com/nextstrain/cli/pull/358>
> Check if Rosetta 2 is enabled in the Conda and Docker runner checks

- .github/workflows/standalone-installers.yaml
- bin/standalone-installer-unix
Conditions on the Nextstrain CLI version being requested, as aarch64 builds¹ will only be available going forward for new releases.  Assumes the next release will be 8.2.0!
Disables Rosetta check when using an aarch64 build, as the checks will be done at the runtime-level instead by `nextstrain setup` and `nextstrain check-setup`.²
We must wait to merge this until after the first release (i.e. 8.2.0) of the changes it depends on above.
¹ <https://github.com/nextstrain/cli/pull/357>
² <https://github.com/nextstrain/cli/pull/361>
> standalone-installer-unix: Use new aarch64 builds for macOS

- doc/index.rst
<https://github.com/nextstrain/docs.nextstrain.org/commit/cb76eebaa60a0a59d8549be264c9260e12254a25>
Fixes CI errors.  Note that the link was never broken for the already-rendered live docs because the move came with redirects from the old target.
> doc: Update cross-ref to a main docs project page that moved

- CHANGES.md
- doc/commands/build.rst
- doc/commands/shell.rst
- doc/commands/view.rst
- nextstrain/cli/runner/__init__.py
Motivated by some of our automation's desire to pass a set of env vars into the runtime without having to munge a user-provided `nextstrain build` invocation.¹
¹ <https://github.com/nextstrain/private/issues/96#issuecomment-2046243636>
> runner: Support NEXTSTRAIN_RUNTIME_ENVDIRS as an alternative to --envdir

- nextstrain/cli/volume.py
The volume named "X" is now only appended to the `opts.volumes` list.
The last usage of the prior functionality, for `opts.build`, was removed in "Better support pathogen repositories which place workflows in subdirectories" (bf858d2).
I think this clarifies a potentially-confusing part of the argument parsing too (e.g. "where did `opts.X` come from?").
Based on #355.
> volume: store_volume("X") no longer sets opts.X

- CHANGES.md
- nextstrain/cli/runner/conda.py
> Bump micromamba to 1.5.8

- .github/workflows/ci.yaml
- CHANGES.md
- setup.py
See commits. Based on #368 but [with fix ups](https://github.com/nextstrain/cli/compare/py311..python-3.12) I'd noted there in review. (I couldn't bring myself to push 3.12 support to a branch named `py311`, so I pushed a new branch.)
> Python 3.12

- CHANGES.md
- doc/commands/build.rst
- nextstrain/cli/command/build.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/aws_batch/s3.py
- nextstrain/cli/util.py
- tests/command-build.py
Excluding files from upload is very handy for ad-hoc skipping of large ancillary files or previous output files in the build directory that the user wants to ignore for the remote build on AWS Batch (i.e. to start it "fresh").  Existing workarounds for the lack of an exclusion mechanism include git worktrees to obtain a clean state and moving files or directories temporarily out of the build directory.
A future improvement would be adding support to also specify these patterns via a file, which can then be checked in to a build repo and shared by all users.
As a broader improvement, I'd like to design away this issue by separating out the workflow-as-program (rules, code, etc.) from the workflow-as-state (config, inputs, outputs, etc.).  This comes out of several other goals, but would …
> build: Add `--exclude-from-upload` and `--exclude-from-download` options

- CHANGES.md
- nextstrain/cli/runner/aws_batch/s3.py
Snakemake stores state information per input/output here and uses it to determine if it needs to re-run rules or not.  It seems akin to the file mtimes which we already take care to preserve on upload/download. Additionally, the metadata recorded is used in Snakemake's report generation and is generally useful for looking at workflow statistics.
Continue to not download all of .snakemake/ en masse because it can potentially contain files that interfere with local usage and/or are large and unnecessary.
Resolves: <https://github.com/nextstrain/cli/issues/373>
Related-to: <https://github.com/nextstrain/docker-base/pull/220>
> runner.aws_batch: Download .snakemake/metadata/ too

- .github/workflows/ci.yaml
- .github/workflows/standalone-installers.yaml
GH Action has removed macos-11 on 28 June 2024.¹
Drop it from two lists and replace it with macos-12 in one list to represent the oldest available macOS runner to build for x86_64-apple-darwin.
¹ <https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal>
- Resolves #375
> Remove/replace macos-11 jobs

- CHANGES.md
- nextstrain/cli/remote/nextstrain_dot_org.py
> remote download: Names with dots

- .github/actions/setup-integration-tests/action.yaml
The latest version will now use Conda's osx-arm64 channel on macOS when available.  As it seems we're encountering issues with osx-64 packages on arm64 hardware¹, let's see if this switch helps avoid those issues.
¹ <https://github.com/nextstrain/cli/issues/382>
Resolves #386
> dev: Upgrade setup-miniconda action from v2 → v3

- doc/aws-batch.md
- doc/conf.py
Per post-merge feedback.
Also add note that the underlying code in the linkchecker uses `re.match()` to evaluate the regular expression, so there's already an implicit start of string anchor in effect, and something like `r'google'` will _NOT_ match anything.
> Anchor regexes and escape potential metachars [#388]

- CHANGES.md
- nextstrain/cli/remote/nextstrain_dot_org.py
Otherwise, for remote origins other than the default of nextstrain.org, the error messages suggest incorrect/misleading possible solutions in the form of commands to run.
Motivated by @jameshadfield's comments in Slack.¹
¹ <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1723760025178909?thread_ts=1723701856.612259&cid=C01LCTT7JNN>
> remote.nextstrain_dot_org: Include an explicit origin in error messages

- nextstrain/cli/runner/conda.py
This started failing recently with newer typeshed stubs for tarfile.open() (and/or newer stubs for requests.Response?).
mypy fails with:
nextstrain/cli/runner/conda.py:220: error: Argument "fileobj" to "open" has incompatible type "Union[HTTPResponse, Any]"; expected "Optional[IO[bytes]]"
and pyright with:
nextstrain/cli/runner/conda.py:220:14 - error: No overloads for "open" match the provided arguments (reportCallIssue)
nextstrain/cli/runner/conda.py:220:58 - error: Argument of type "Literal['r|*']" cannot be assigned to parameter "mode" of type "_FileCreationModes" in function "open"
  Type "Literal['r|*']" is not assignable to type "_FileCreationModes"
    "Literal['r|*']" is not assignable to type "Literal['a']"
    "Literal['r|*']" is not assignable to type "Literal['w']" …
> runner.conda: Ignore newly failing type check for tarfile.open()

- devel/pyoxidizer
Taking the first line never worked as intended, as the input from echo was never multi-line but space-separated words.  orz
Reverse version sort for good measure to use the newest version instead of oldest if we have more than one (which was how I ran into this bug in the first place).
> devel/pyoxidizer: Correctly locate just one already-downloaded PyOxidizer binary

- .github/actions/setup-integration-tests/action.yaml
Scheduled CI runs today failed¹ due to a Mambaforge brownout ahead of its removal in January 2025; it was deprecated in late July 2024.²
¹ <https://github.com/nextstrain/cli/actions/runs/11130647037/job/30930449798#step:3:135>
² <https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/>
> dev: Stop using Mambaforge in CI; the Miniforge installer is now equivalent

- .github/actions/setup-integration-tests/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/standalone-installers.yaml
macOS 12 was deprecated in August and will be removed by December.¹  I moved the build and test jobs to the next oldest version, macOS 13.
Ubuntu 24.04 was released in late September,² so test on it.
macOS 15 was released for beta in late September,² so test on it too.
Test the x86_64 binary on macOS 14 and 15 too since it should work with Rosetta.  I'm not sure why it wasn't tested on macOS 14 previously; maybe just an oversight?
¹ <https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/>
² <https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/>
> dev: Update GitHub runners used by CI

- CHANGES.md
- nextstrain/cli/runner/aws_batch/__init__.py
For completed jobs, it's more useful to continue on with printing the job status (e.g. success or reason for failure) and downloading job results even if an error occurs when fetching logs.  As a concrete example, we've observed cases where a failed job has a log stream associated with it in Batch but that log stream does not actually exist in CloudWatch Logs.¹  The log fetch error hid the reason for job failure, hampering troubleshooting.
¹ <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1730406138009409>
> runner.aws_batch: Gracefully handle errors when fetching logs for completed jobs

- .readthedocs.yml
Previously we relied on RTD's auto-detection of the Sphinx configuration file.  That's being deprecated for good on 20 January 2025, with temporary brownouts starting on 6 Jan.¹
¹ <https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/>
> dev: Explicitly point Read The Docs at our Sphinx configuration file

- CHANGES.md
- nextstrain/cli/command/view.py
- nextstrain/cli/net.py
Skip 'em instead of erroring.  Brought to attention by a typeshed update for the standard library that adds tuple[int, bytes] as a potential sockaddr value from getaddrinfo() when running Python compiled with --disable-ipv6 on a system that enables IPv6.  Such a value reflects the underlying libc sockaddr struct and is not directly usable without bypassing the disabling of IPv6.  The stdlib's type signature doesn't reflect the full constraints on actual return values—i.e. under what conditions each value type is actually returned—so the type checker is under-informed and requires some muzzling.
Resolves <https://github.com/nextstrain/cli/issues/411>.
> Gracefully handle IPv6 sockaddrs when Python's compiled without IPv6 support

- CHANGES.md
- nextstrain/cli/net.py
Our is_loopback() implements three-valued logic (True, False, None) but all() implements boolean logic, so we need to handle the empty case ourself.  Oops!
Noticed while testing an IPv6-only host against a Python with IPv6 disabled, which made it unresolvable.  See "Gracefully handle IPv6 sockaddrs when Python's compiled without IPv6 support" (06e830b).
> net: Don't consider a host that we can't resolve as having a loopback address

- CHANGES.md
- nextstrain/cli/command/view.py
Not bracketing caused invalid URLs the browser couldn't open.
Hoists the bracketing concern out of print_url() and up a stack level where it can be reused.
> view: Bracket an IPv6 address in the URL opened in the browser

- CHANGES.md
- nextstrain/cli/runner/docker.py
There is now no caveat¹ of AWS Batch overlays being partial while Docker and Singularity overlays are complete.  Overlays are complete and behave the same across containerized runtimes.
Spurred by conversation in review² and realizing, after some tinkering, that it would not take too much extra effort after all to implement in the image entrypoint.
¹ As mentioned in "runner.aws_batch: Support overlay volumes (e.g.
--augur)" (99168ac).
² <https://github.com/nextstrain/cli/pull/419#discussion_r1982432118>
> runner.aws_batch: Bump minimum Docker image required for overlays on AWS Batch

- nextstrain/cli/command/check_setup.py
- nextstrain/cli/command/setup.py
- nextstrain/cli/runner/ambient.py
- nextstrain/cli/runner/aws_batch/__init__.py
- nextstrain/cli/runner/conda.py
- nextstrain/cli/runner/docker.py
- nextstrain/cli/runner/singularity.py
- nextstrain/cli/types.py
- nextstrain/cli/util.py
setup and check-setup commands can take several seconds for certain runtimes. Improve user experience by showing progress as it happens.
Closes #359
> Unbuffer runner test results

- .github/workflows/ci.yaml
- .github/workflows/standalone-installers.yaml
Remove ubuntu-20.04 since GH Actions has officially ended support for it on 2025-04-15.
<https://github.com/actions/runner-images/issues/11101>
Following up to https://github.com/nextstrain/.github/issues/122#issuecomment-2651855979
> GH workflows: Remove ubuntu-20.04

- CHANGES.md
- nextstrain/cli/util.py
This gives us insights into usage and also more flexibility to shift how we're releasing and distributing it.
Related-to: <https://github.com/nextstrain/nextstrain.org/pull/1160>
Replaces/incorporates #433.
> util: Fetch our own latest version via nextstrain.org instead of pypi.org

- CHANGES.md
- nextstrain/cli/rst/__init__.py
- nextstrain/cli/runner/conda.py
- pyrightconfig.json
It seems like it will prove useful to be able to force a particular subdir for both testing/development and as a workaround to issues with specific subdirs on platforms that support more than one (e.g. forcing osx-64 instead of osx-arm64, if osx-arm64 is broken in some way).
I thought about implementing this along with my recent subdir handling changes, but I thought maybe YAGNI and deferred.  The slew of issues recently uncovered with osx-arm64 though made me reconsider and JFDI.
> runner.conda: Allow overriding of subdir selection

- .readthedocs.yml
- devel/generate-changes-doc
- devel/generate-doc
- devel/rtd-pre-build
- doc/Makefile
- doc/aws-batch.md
- doc/changes.md
- doc/conf.py
- doc/development.md
- doc/index.rst
- setup.py
- tests/doc.py
This has been a longstanding omission that I finally got around to correcting because I wanted to more publicly link to the changelog and not point people into the den of source-ry that is GitHub.
I did this thing not because it was easy, but because I *thought* it would be easy: just drop in CHANGES.md as-is using an "include" directive. Well, after much gnashing of keys, it turns out that usable heading anchors are impossible to achieve with this method unless we make CHANGES.md include noisy MyST syntax. So I swapped to doc generation/transformation instead.
> docs: Include a changelog in the documentation

- .github/workflows/ci.yaml
- .github/workflows/standalone-installers.yaml
Windows Server 2019 has been scheduled for deprecation and will be [removed by end of June](https://github.com/actions/runner-images/issues/12045).  I moved the build job to the next oldest version, Windows Server 2022.
Windows Server 2025 was [released in December 2024](https://github.com/actions/runner-images/issues/11228), so test on it.
Closes https://github.com/nextstrain/.github/issues/131
> dev: Update Windows GitHub runners

- CHANGES.md
- doc/changes.md
- nextstrain/cli/command/build.py
- nextstrain/cli/runner/aws_batch/s3.py
When using Snakemakes storage support to download remote files, Snakemake stores  the downloaded files in `.snakemake/storage` by default. This allows users to  keep the remote files that were downloaded during the build on AWS Batch.
Note that the storage path is configurable via Snakemake's  `--local-storage-prefix`.¹ So if someone configures the storage path to a custom  path within `.snakemake`, e.g. `.snakemake/foo`, then it would not be available  in their downloaded workdir. I'm not even sure it's possible to configure the path in entrypoint-aws-batch for the docker-base image, so I've added a warning against using the Snakemake option if using the aws-batch runtime.
Resolves https://github.com/nextstrain/cli/issues/453
Depends on https://github.com/nextstrain/docker-base/pull/259 …
> runner.aws_batch: Download .snakemake/storage/ too

- CHANGES.md
- doc/changes.md
- nextstrain/cli/util.py
Sets DESTINATION to the installation path we're running under so the new version is installed to the same place, rather than the default path.
This muddies the commands but makes them behave better, which is more important.  Particularly since soon we'll offer to run these commands automatically for the user.
> util: Account for non-default standalone installation paths in suggested update command

- CHANGES.md
- doc/changes.md
- doc/commands/run.rst
- nextstrain/cli/command/run.py
- nextstrain/cli/pathogens.py
This decoupling of workflow names from paths was always expected and intended to be possible, and now it is.
Related-to: <https://github.com/nextstrain/zika-tutorial/pull/19>
Related-to: <https://github.com/nextstrain/public/issues/1>
> run: Resolve workflow names using pathogen registration, if available
